<?php

namespace PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends EntityRepository
{

	public function getScoreLikeName($name) {
		$query = $this->createQueryBuilder('a')
               ->where("a.problem LIKE :my_name")
			   ->setParameter('my_name', '%'.$name.'%')
               ->getQuery();
			   
		return $query->getResult();
	}

}
