<?php

namespace PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScoreTMPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreTMPRepository extends EntityRepository
{
}
