admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"