<?php

namespace Proxies\__CG__\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \AdminBundle\Entity\Notification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'id', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'user', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'message', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'dateNotif', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'seen', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'dateSeen');
        }

        return array('__isInitialized__', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'id', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'user', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'message', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'dateNotif', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'seen', '' . "\0" . 'AdminBundle\\Entity\\Notification' . "\0" . 'dateSeen');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNotif($dateNotif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNotif', array($dateNotif));

        return parent::setDateNotif($dateNotif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNotif', array());

        return parent::getDateNotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeen($seen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeen', array($seen));

        return parent::setSeen($seen);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeen', array());

        return parent::getSeen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSeen($dateSeen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSeen', array($dateSeen));

        return parent::setDateSeen($dateSeen);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSeen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSeen', array());

        return parent::getDateSeen();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AdminBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

}
